[target.'cfg(target_arch = "riscv32")']
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[env]
ESP_LOG = "info"
SSID = "SSID"
PASSWORD = "PASSWORD"
STATIC_IP = "1.1.1.1 "
GATEWAY_IP = "1.1.1.1"
HOST_IP = "1.1.1.1"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE="65536"

[unstable]
build-std = ["alloc", "core"]
