# TODO: From https://github.com/thecodechemist99/pinetime-rust
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF52832_xxAA with your chip as listed in `probe-run --list-chips`
#runner = "probe-run --chip nRF52832_xxAA"
